site_name: NFC Wiki
copyright: 'Copyright &copy; 2019-2021 nfcim. All Rights Reserved.'

theme:
  name: material
  language: zh

nav:
  - 概述: index.md
  - 智能卡手册:
    - 概述: cards/index.md
    - 交通卡:
      - 北京市政交通一卡通: cards/transportation/bmac.md
      - 交通联合卡: cards/transportation/tunion.md

plugins:
  - mermaid2
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
  - git-authors:
      show_contribution: true
      show_line_count: true