site_name: NFC Wiki
copyright: 'Copyright &copy; 2019-2021 nfcim. All Rights Reserved.'

theme:
  name: material
  language: zh

nav:
  - 概述: index.md
  - 智能卡手册:
    - 概述: cards/index.md
    - 通用部分:
      - 电子钱包: cards/general/purse.md
    - 交通卡:
      - 交通联合卡: cards/transportation/tunion.md
      - 数字城市一卡通: cards/transportation/cityunion.md
      - 北京市政交通一卡通: cards/transportation/bmac.md
      - 深圳通: cards/transportation/shenzhentong.md
      - 岭南通: cards/transportation/lingnanpass.md
      - 武汉通: cards/transportation/wuhantong.md
      - 八达通: cards/transportation/octopus.md
      - EZ-Link: cards/transportation/ezlink.md

plugins:
  - mermaid2
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
  - git-authors:
      show_contribution: true
      show_line_count: true